/*
 * shellcode.c - position-independent x64 shellcode demo payload.
 *
 * The .sc section is extracted to a raw binary, AES-256-CBC encrypted, and
 * embedded in the demo DLL (build/payload_sc.h). The DLL's DllMain decrypts
 * it into an executable buffer and runs it.
 *
 * Variants (selected at compile time):
 *   -DSHELLCODE_MARKER : PEB walk -> kernel32 -> CreateFileA/WriteFile/
 *                        CloseHandle, write "shellcode_marker.txt"
 *                        (headless validation artifact)
 *   -DSHELLCODE_MSGBOX : PEB walk -> user32 -> MessageBoxA
 *
 * Constraints honored so the extracted bytes are fully self-contained:
 *   - every function lives in the .sc section and is static (assembler
 *     resolves intra-section relative calls; the blob carries no relocations)
 *   - no global/static data, no string literals (stack byte arrays only)
 *   - no external calls (all APIs are reached through resolved pointers)
 *   - stack frame < 4 KB (no __chkstk_ms prologue)
 */
#include <intrin.h>

#include "sc_hashes.h"   /* generated by build.py: djb2 name hashes */

typedef unsigned __int64 u64;
typedef unsigned int     u32;
typedef unsigned short   u16;
typedef unsigned char    u8;

#define SC __attribute__((section(".sc"), noinline, used))

/* djb2 over a NUL-terminated ASCII export name (case-sensitive) */
SC static u32 sc_hash(const char *s) {
    u32 h = 5381;
    while (*s) h = h * 33 + (u8)*s++;
    return h;
}

/* djb2 over a wide module base name (case-insensitive). Hashes only the
 * base name up to the first '.' so "kernel32.dll" and "KERNEL32.DLL" both
 * hash identically to build.py's djb2("kernel32"). */
SC static u32 sc_hash_w(const u16 *s, u32 len_bytes) {
    u32 h = 5381;
    for (u32 i = 0; i < len_bytes / 2; i++) {
        u8 c = (u8)s[i];
        if (c == '.') break;
        if (c >= 'A' && c <= 'Z') c = (u8)(c + 32);
        h = h * 33 + c;
    }
    return h;
}

/* walk PEB->Ldr->InMemoryOrderModuleList, return base of module by hash */
SC static u64 sc_find_module(u32 target) {
    u64 peb = __readgsqword(0x60);
    if (!peb) return 0;
    u64 ldr = *(u64 *)(peb + 0x18);
    if (!ldr) return 0;
    u64 head = ldr + 0x20;               /* InMemoryOrderModuleList sentinel */
    u64 cur = *(u64 *)head;              /* first entry's Flink */
    while (cur && cur != head) {
        u64 entry = cur - 0x10;          /* LDR_DATA_TABLE_ENTRY */
        u16 len = *(u16 *)(entry + 0x58);    /* BaseDllName.Length */
        u16 *buf = *(u16 **)(entry + 0x60);  /* BaseDllName.Buffer */
        if (buf && len && sc_hash_w(buf, len) == target)
            return *(u64 *)(entry + 0x30);   /* DllBase */
        cur = *(u64 *)cur;               /* Flink */
    }
    return 0;
}

/* export-table lookup by name hash; returns 0 for forwarders */
SC static u64 sc_get_proc(u64 base, u32 target) {
    if (!base) return 0;
    if (*(u16 *)base != 0x5a4d) return 0;      /* "MZ" */
    u32 lfanew = *(u32 *)(base + 0x3c);
    u64 pe = base + lfanew;
    u32 exp_rva = *(u32 *)(pe + 0x88);         /* PE32+ export dir RVA */
    u32 exp_sz  = *(u32 *)(pe + 0x8c);
    if (!exp_rva) return 0;
    u64 exp = base + exp_rva;
    u32 nnames = *(u32 *)(exp + 0x18);
    u32 names  = *(u32 *)(exp + 0x20);
    u32 ords   = *(u32 *)(exp + 0x24);
    u32 funcs  = *(u32 *)(exp + 0x1c);
    for (u32 i = 0; i < nnames; i++) {
        u32 nrva = *(u32 *)(base + names + i * 4);
        if (!nrva) continue;
        if (sc_hash((const char *)(base + nrva)) != target) continue;
        u16 o = *(u16 *)(base + ords + i * 2);
        u32 frva = *(u32 *)(base + funcs + (u32)o * 4);
        if (frva >= exp_rva && frva < exp_rva + exp_sz) return 0; /* forwarder */
        return base + frva;
    }
    return 0;
}

#ifdef SHELLCODE_MARKER

SC static int sc_marker(void) {
    u64 k32 = sc_find_module(HASH_KERNEL32);
    u64 pCreateFileA = sc_get_proc(k32, HASH_CREATEFILEA);
    u64 pWriteFile   = sc_get_proc(k32, HASH_WRITEFILE);
    u64 pCloseHandle = sc_get_proc(k32, HASH_CLOSEHANDLE);
    if (!pCreateFileA || !pWriteFile || !pCloseHandle) return 1;

    /* "shellcode_marker.txt" */
    u8 fname[] = { 0x73,0x68,0x65,0x6c,0x6c,0x63,0x6f,0x64,0x65,0x5f,
                   0x6d,0x61,0x72,0x6b,0x65,0x72,0x2e,0x74,0x78,0x74, 0 };
    /* "reflective loader: encrypted shellcode executed\r\n" */
    u8 msg[] = { 0x72,0x65,0x66,0x6c,0x65,0x63,0x74,0x69,0x76,0x65,0x20,
                 0x6c,0x6f,0x61,0x64,0x65,0x72,0x3a,0x20,
                 0x65,0x6e,0x63,0x72,0x79,0x70,0x74,0x65,0x64,0x20,
                 0x73,0x68,0x65,0x6c,0x6c,0x63,0x6f,0x64,0x65,0x20,
                 0x65,0x78,0x65,0x63,0x75,0x74,0x65,0x64, 0x0d, 0x0a, 0 };
    u32 written = 0;
    typedef u64 (*fn_CreateFileA)(const char *, u32, u32, void *, u32, u32, void *);
    typedef u64 (*fn_WriteFile)(u64, const char *, u32, u32 *, void *);
    typedef u64 (*fn_CloseHandle)(u64);
    u64 h = ((fn_CreateFileA)pCreateFileA)((const char *)fname,
                                           0x40000000 /*GENERIC_WRITE*/, 0, 0,
                                           2 /*CREATE_ALWAYS*/, 0x80, 0);
    if (h == (u64)-1) return 1;
    ((fn_WriteFile)pWriteFile)(h, (const char *)msg, sizeof(msg) - 1, &written, 0);
    ((fn_CloseHandle)pCloseHandle)(h);
    return 0;
}

#else /* SHELLCODE_MSGBOX */

SC static int sc_msgbox(void) {
    u64 u32mod = sc_find_module(HASH_USER32);
    u64 pMessageBoxA = sc_get_proc(u32mod, HASH_MESSAGEBOXA);
    if (!pMessageBoxA) return 1;
    /* "reflective loader: encrypted shellcode executed" */
    u8 msg[] = { 0x72,0x65,0x66,0x6c,0x65,0x63,0x74,0x69,0x76,0x65,0x20,
                 0x6c,0x6f,0x61,0x64,0x65,0x72,0x3a,0x20,
                 0x65,0x6e,0x63,0x72,0x79,0x70,0x74,0x65,0x64,0x20,
                 0x73,0x68,0x65,0x6c,0x6c,0x63,0x6f,0x64,0x65,0x20,
                 0x65,0x78,0x65,0x63,0x75,0x74,0x65,0x64, 0 };
    /* "reflective-loader" */
    u8 cap[] = { 0x72,0x65,0x66,0x6c,0x65,0x63,0x74,0x69,0x76,0x65,
                 0x2d,0x6c,0x6f,0x61,0x64,0x65,0x72, 0 };
    typedef u64 (*fn_MessageBoxA)(u64, const char *, const char *, u32);
    ((fn_MessageBoxA)pMessageBoxA)(0, (const char *)msg, (const char *)cap, 0);
    return 0;
}

#endif

/* blob entry point: called by the DLL after decryption */
SC void sc_entry(void) {
#ifdef SHELLCODE_MARKER
    sc_marker();
#else
    sc_msgbox();
#endif
}
